"""post_id in feed

Revision ID: be3c14821f3a
Revises: fc90eefc84e4
Create Date: 2024-02-07 13:05:47.518577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3c14821f3a'
down_revision: Union[str, None] = 'fc90eefc84e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('post_id', sa.Uuid(), nullable=False))
    op.drop_constraint('feeds_user_id_fkey', 'feeds', type_='foreignkey')
    op.drop_constraint('feeds_author_id_fkey', 'feeds', type_='foreignkey')
    op.create_foreign_key(None, 'feeds', 'users', ['author_id'], ['id'], source_schema='content', referent_schema='content')
    op.create_foreign_key(None, 'feeds', 'users', ['user_id'], ['id'], source_schema='content', referent_schema='content')
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], source_schema='content', referent_schema='content')
    op.drop_constraint('subscriptions_user_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_subscriber_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], source_schema='content', referent_schema='content')
    op.create_foreign_key(None, 'subscriptions', 'users', ['subscriber_id'], ['id'], source_schema='content', referent_schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', schema='content', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', schema='content', type_='foreignkey')
    op.create_foreign_key('subscriptions_subscriber_id_fkey', 'subscriptions', 'users', ['subscriber_id'], ['id'])
    op.create_foreign_key('subscriptions_user_id_fkey', 'subscriptions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'posts', schema='content', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'feeds', schema='content', type_='foreignkey')
    op.drop_constraint(None, 'feeds', schema='content', type_='foreignkey')
    op.create_foreign_key('feeds_author_id_fkey', 'feeds', 'users', ['author_id'], ['id'])
    op.create_foreign_key('feeds_user_id_fkey', 'feeds', 'users', ['user_id'], ['id'])
    op.drop_column('feeds', 'post_id')
    # ### end Alembic commands ###
