"""posts

Revision ID: 43d5b6479d01
Revises: 85ec469f2794
Create Date: 2024-02-06 17:12:57.917775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d5b6479d01'
down_revision: Union[str, None] = '85ec469f2794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_index('user_id_idx', 'posts', ['user_id'], unique=False, schema='content')
    op.drop_constraint('subscriptions_user_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_subscriber_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], source_schema='content', referent_schema='content')
    op.create_foreign_key(None, 'subscriptions', 'users', ['subscriber_id'], ['id'], source_schema='content', referent_schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', schema='content', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', schema='content', type_='foreignkey')
    op.create_foreign_key('subscriptions_subscriber_id_fkey', 'subscriptions', 'users', ['subscriber_id'], ['id'])
    op.create_foreign_key('subscriptions_user_id_fkey', 'subscriptions', 'users', ['user_id'], ['id'])
    op.drop_index('user_id_idx', table_name='posts', schema='content')
    op.drop_table('posts', schema='content')
    # ### end Alembic commands ###
