"""feeds

Revision ID: fc90eefc84e4
Revises: 43d5b6479d01
Create Date: 2024-02-06 21:31:55.821463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc90eefc84e4'
down_revision: Union[str, None] = '43d5b6479d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['content.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_index('user_id_date_idx', 'feeds', ['user_id', 'creation_date'], unique=False, schema='content')
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], source_schema='content', referent_schema='content')
    op.drop_constraint('subscriptions_user_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_subscriber_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], source_schema='content', referent_schema='content')
    op.create_foreign_key(None, 'subscriptions', 'users', ['subscriber_id'], ['id'], source_schema='content', referent_schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', schema='content', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', schema='content', type_='foreignkey')
    op.create_foreign_key('subscriptions_subscriber_id_fkey', 'subscriptions', 'users', ['subscriber_id'], ['id'])
    op.create_foreign_key('subscriptions_user_id_fkey', 'subscriptions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'posts', schema='content', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'])
    op.drop_index('user_id_date_idx', table_name='feeds', schema='content')
    op.drop_table('feeds', schema='content')
    # ### end Alembic commands ###
