"""ondelete user_id cascade

Revision ID: e0f141362e35
Revises: be3c14821f3a
Create Date: 2024-02-07 15:59:02.687588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f141362e35'
down_revision: Union[str, None] = 'be3c14821f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feeds_user_id_fkey', 'feeds', type_='foreignkey')
    op.drop_constraint('feeds_author_id_fkey', 'feeds', type_='foreignkey')
    op.create_foreign_key(None, 'feeds', 'users', ['author_id'], ['id'], source_schema='content', referent_schema='content', ondelete='CASCADE')
    op.create_foreign_key(None, 'feeds', 'users', ['user_id'], ['id'], source_schema='content', referent_schema='content', ondelete='CASCADE')
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], source_schema='content', referent_schema='content', ondelete='CASCADE')
    op.drop_constraint('subscriptions_subscriber_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_user_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], source_schema='content', referent_schema='content', ondelete='CASCADE')
    op.create_foreign_key(None, 'subscriptions', 'users', ['subscriber_id'], ['id'], source_schema='content', referent_schema='content', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', schema='content', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', schema='content', type_='foreignkey')
    op.create_foreign_key('subscriptions_user_id_fkey', 'subscriptions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('subscriptions_subscriber_id_fkey', 'subscriptions', 'users', ['subscriber_id'], ['id'])
    op.drop_constraint(None, 'posts', schema='content', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'feeds', schema='content', type_='foreignkey')
    op.drop_constraint(None, 'feeds', schema='content', type_='foreignkey')
    op.create_foreign_key('feeds_author_id_fkey', 'feeds', 'users', ['author_id'], ['id'])
    op.create_foreign_key('feeds_user_id_fkey', 'feeds', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
